### ISSUE TITLE
The message signature is invalid.

### ISSUE THREAD

**Issue by JeanLebrument** [aws/aws-js-sns-message-validator#6] opened 2016-09-28 16:37 UTC
Hello,

Thanks for the work carried out!

I keep having the following error message: "The message signature is invalid."

I added a `console.log` before the `verifier.verify` method call to display the certificate and the signature. Both look correct. 

Any suggestions on how to debug this?

Regards,
Jean

**Comment by jeskew** [comment] 2016-12-08 22:10
Could you try with the version 0.2.2? I saw a similar error in some versions of node when messages contained utf-8 characters.

**Comment by jeskew** [comment] 2017-02-19 17:22
I believe this should be fixed in the latest tagged release. Please feel free to reopen if the issue is visible with version >= 0.2.2.

**Closed as completed by jeskew** 2017-02-19 17:22 UTC
Labels: guidance
